apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-app
  labels:
    app: js-app
spec:
  replicas:
  selector:
    matchLabels:
      app: js-app
  template:
    metadata:
      labels:
        app: js-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: js-app
        image: 493739114887.dkr.ecr.eu-north-1.amazonaws.com/js-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
